let fonts = [
	"Alata",
	"Audiowide",
	"Abel",
	"Aladin",
	"Abril Fatface",
	"Poller One",
	"Anton",
	"Dancing Script",
	"Droid Sans",
	"Droid Serif",
	"Gloria Hallelujah",
	"Indie Flower",
	"Lato",
	"Lobster",
	"Lobster Two",
	"Sacramento",
	"Homemade Apple",
	"Lora",
	"Oswald",
	"PT Sans",
	"PT Serif",
	"Pacifico",
	"Poppins",
	"Nunito",
	"Questrial",
	"Playfair Display",
	"Raleway",
	"Roboto",
	"Roboto Condensed",
	"Roboto Slab",
	"Rubik",
	"Source Sans Pro",
	"Ubuntu",
	"Monoton",
	"Bungee Inline",
	"Black Ops One",
	"Finger Paint",
	"Bungee Shade",
	"Ribeye Marrow",
	"Suez One",
	"Teko",
	"Josefin Sans",
	"Acme",
	"Varela Round",
	"Archivo Black",
	"Berkshire Swash",
	"Righteous",
	"Concert One",
	"Fredoka One",
	"DM Sans",
	"ABeeZee",
	"Cinzel",
	"Limelight",
	"Cabin Sketch",
	"Electrolize",
	"Niconne",
	"Aclonica",
	"Reem Kufi",
	"Love Ya Like A Sister",
	"Vast Shadow",
	"Ravi Prakash",
	"Germania One",
	"Nosifer",
	"Pirata One",
	"Rubik Mono One",
	"Butcherman",
	"Great Vibes",
	"Teko",
	"Quicksand",
	"Comfortaa",
	"Montserrat",
	"Bree Serif",
	"Francois One",
	"Kaushan Script",
	"Marck Script",
	"Patua One",
	"Permanent Marker",
	"Alfa Slab One",
	"Cookie",
	"Lalezar",
	"Patrick Hand",
	"Passion One",
	"Boogaloo",
	"Paytone One",
	"Playball",
	"Fugaz One",
	"Oleo Script",
	"Knewave",
	"Bevan",
	"Faster One",
	"Leckerli One",
	"Bungee",
	"Pattaya",
	"Rye",
	"Federo",
	"Nova Square",
	"Ranchers",
	"New Rocker",
	"Permanent Marker",
	"Mr Dafoe",
	"Yesteryear",
	"Signika",
];
export default fonts;
