const pageNames = {
	PAGE_TEMPLATE_EDITOR: "PAGE_TEMPLATE_EDITOR",
	PAGE_VIDEO_EDITOR: "PAGE_VIDEO_EDITOR",
	PAGE_RENDER_USER_VIDEO: "PAGE_RENDER_USER_VIDEO",
	PAGE_RENDER_ADMIN_TEMPLATE: "PAGE_RENDER_ADMIN_TEMPLATE",
	PAGE_REMOTE_RENDER: "PAGE_REMOTE_RENDER",
};

export default pageNames;
